spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://dlvdb.project2-hc-scm.cloud:15432/db_delivery
    username: dlv_admin
    password: dlv_1234

  data:
    redis:
      host: dlvredis.project2-hc-scm.cloud
      port: 16379

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: false
    show-sql: false

  kafka:
    bootstrap-servers: "b-1.hcscmmsk.qhxzwx.c3.kafka.ap-northeast-2.amazonaws.com:9096,b-2.hcscmmsk.qhxzwx.c3.kafka.ap-northeast-2.amazonaws.com:9096,b-3.hcscmmsk.qhxzwx.c3.kafka.ap-northeast-2.amazonaws.com:9096"

    consumer:
      group-id: delivery-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      properties:
        spring.json.trusted.packages: "*"
        security.protocol: SASL_SSL
        sasl.mechanism: SCRAM-SHA-512
        sasl.jaas.config: org.apache.kafka.common.security.scram.ScramLoginModule required username='DLV' password='${MSK_PASSWORD:CHIlx0xjZFypwUMg8Angy3Ym}';

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      properties:
        security.protocol: SASL_SSL
        sasl.mechanism: SCRAM-SHA-512
        sasl.jaas.config: org.apache.kafka.common.security.scram.ScramLoginModule required username='DLV' password='${MSK_PASSWORD:CHIlx0xjZFypwUMg8Angy3Ym}';

    properties:
      security.protocol: SASL_SSL
      sasl.mechanism: SCRAM-SHA-512
      sasl.jaas.config: org.apache.kafka.common.security.scram.ScramLoginModule required username='DLV' password='${MSK_PASSWORD:CHIlx0xjZFypwUMg8Angy3Ym}';

  cloud:
    aws:
      credentials:
        access-key: ${AWS_ACCESS_KEY:test-access-key}
        secret-key: ${AWS_SECRET_KEY:test-secret-key}
      s3:
        bucket: ${AWS_S3_BUCKET:scm-delivery-pod-bucket}
      region:
        static: ap-northeast-2

slack:
  webhook-url: ${SLACK_WEBHOOK_URL:https://hooks.slack.com/services/YOUR/SLACK/WEBHOOK}

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    path: /swagger-ui/index.html

sender:
  name: "hc_scm"
  phone: "02-1234-5678"
  address: "경기도 안산시 단원구 원곡동 828-6"