# 기존 내용 아래에 추가
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://db.project2-hc-scm.cloud:15432/db_delivery
    username: dlv_admin
    password: dlv_1234

  data:
    redis:
      host: redis.project2-hc-scm.cloud
      port: 16379

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: false
    show-sql: false

  kafka:
    bootstrap-servers: b-1.scmmsk.ymo1mq.c3.kafka.ap-northeast-2.amazonaws.com:9096,b-2.scmmsk.ymo1mq.c3.kafka.ap-northeast-2.amazonaws.com:9096,b-3.scmmsk.ymo1mq.c3.kafka.ap-northeast-2.amazonaws.com:9096

    consumer:
      group-id: delivery-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      properties:
        spring.json.trusted.packages: "*"
        security.protocol: SASL_SSL
        sasl.mechanism: SCRAM-SHA-512
        sasl.jaas.config: 'org.apache.kafka.common.security.scram.ScramLoginModule required username="scm-msk_DLV" password="CHIlx0xjZFypwUMg8Angy3Ym";'

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      properties:
        security.protocol: SASL_SSL
        sasl.mechanism: SCRAM-SHA-512
        sasl.jaas.config: 'org.apache.kafka.common.security.scram.ScramLoginModule required username="scm-msk_DLV" password="CHIlx0xjZFypwUMg8Angy3Ym";'

    properties:
      security.protocol: SASL_SSL
      sasl.mechanism: SCRAM-SHA-512
      sasl.jaas.config: 'org.apache.kafka.common.security.scram.ScramLoginModule required username="scm-msk_DLV" password="CHIlx0xjZFypwUMg8Angy3Ym";'

  cloud:
    aws:
      credentials:
        access-key: ${AWS_ACCESS_KEY:test-access-key}
        secret-key: ${AWS_SECRET_KEY:test-secret-key}
      s3:
        bucket: ${AWS_S3_BUCKET:scm-delivery-pod-bucket}
      region:
        static: ap-northeast-2

# 🚀 슬랙 알림 웹후크 연동 설정
slack:
  webhook-url: https://hooks.slack.com/services/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

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    path: /swagger-ui/index.html

# --------------------------------------------------
# 📦 출발지 (창고/쇼핑몰) 고정 정보
# --------------------------------------------------
sender:
  name: "hc_scm"
  phone: "02-1234-5678"
  address: "경기도 안산시 단원구 원곡동 828-6"