spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://scm-delivery-db.cbksaccgu2u3.ap-northeast-2.rds.amazonaws.com:5432/scm_delivery_db
    username: postgres
    password: anhs12080726!

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    path: /swagger-ui/index.html