apiVersion: apps/v1
kind: Deployment
metadata:
  name: scm-delivery-deployment
  namespace: default
  labels:
    app: scm-delivery
spec:
  replicas: 2
  selector:
    matchLabels:
      app: scm-delivery
  template:
    metadata:
      labels:
        app: scm-delivery
    spec:
      containers:
        - name: scm-delivery-app
          image: 967996001868.dkr.ecr.ap-northeast-2.amazonaws.com/delivery-service:latest
          ports:
            - containerPort: 8080
          env:
            - name: MSK_PASSWORD
              value: "lnm12e5SNENA4FV9lyfsZIeN"
          resources:
            requests:
              cpu: "250m"
              memory: "512Mi"
            limits:
              cpu: "500m"
              memory: "1Gi"